### Scratch - for testing python code

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.vstack((a, b))  # Stacks vertically
d = np.hstack((a, b))  # Stacks horizontally

print(c)
print(d)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b), axis=0)
print(c)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

c = np.concatenate((a, b), axis=0)
print(c)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.append(a, b)
print(c)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

c = np.append(a, b)
print(c)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
import numpy as np

# Original stats array
stats = np.array([17, 74, 33, 82, 51, 31])

# 2-dimensional weights array
weights = np.array([
    [3, -4, 2, -2, -1, -1],
    [-2, 1, 2, -2, -1, -1],
    # Add up to 252 sets of weights
])

# Add the weights to the stats array using broadcasting
results = stats + weights

print(results)

In [4]:
import numpy as np

# Original stats array
stats = np.array([17, 74, 33, 82, 51, 31])

# 2-dimensional weights array with multiple sets of weights
weights = np.array([
    [3, -4, 2, -2, -1, -1],
    [-2, 1, 2, -2, -1, -1],
    [3, -3, 3, -2, -1, -1],
    [-2, 1, 2, -2, -1, -1],
    # Add more sets of weights as needed, up to 252
])

# Add the weights to the stats array using broadcasting
results = stats + weights

# Function to round down to the nearest 5
def round_down_to_nearest_5(x):
    return x // 5 * 5

# Apply the rounding function using numpy vectorization
rounded_results = round_down_to_nearest_5(results)

# Use numpy's unique function to get unique rows
unique_results = np.unique(rounded_results, axis=0)

# Print the results
print(unique_results)

[[15 75 35 80 50 30]
 [20 70 35 80 50 30]]


In [5]:
import numpy as np

# Example 3D array
array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
])

# Find unique 2D slices along the first axis (axis=0)
unique_slices_axis0 = np.unique(array_3d, axis=0)

# Find unique 2D slices along the second axis (axis=1)
unique_slices_axis1 = np.unique(array_3d, axis=1)

# Find unique 1D slices along the third axis (axis=2)
unique_slices_axis2 = np.unique(array_3d, axis=2)

print("Unique slices along axis=0:")
print(unique_slices_axis0)

print("Unique slices along axis=1:")
print(unique_slices_axis1)

print("Unique slices along axis=2:")
print(unique_slices_axis2)

Unique slices along axis=0:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Unique slices along axis=1:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Unique slices along axis=2:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#  Lance DB testing
https://github.com/lancedb/lancedb

In [8]:
%%bash
pip install lancedb
pip install ipywidgets

In [9]:
import lancedb

uri = "data/sample-lancedb"
db = lancedb.connect(uri)
table = db.create_table("my_table",
                         exist_ok=True,
                         data=[{"vector": [3.1, 4.1], "item": "foo", "price": 10.0},
                               {"vector": [5.9, 26.5], "item": "bar", "price": 20.0}])
result = table.search([100, 100]).limit(2).to_pandas()
result

vector item  price     _distance
0  [5.9, 26.5]  bar   20.0  14257.059570
1   [3.1, 4.1]  foo   10.0  18586.421875

In [ ]:
# todo: see what the performance is if we insert all the armor pieces into a lancedb table and then query for the best outfits