### Scratch - for testing python code

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.vstack((a, b))  # Stacks vertically
d = np.hstack((a, b))  # Stacks horizontally

print(c)
print(d)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b), axis=0)
print(c)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

c = np.concatenate((a, b), axis=0)
print(c)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.append(a, b)
print(c)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

c = np.append(a, b)
print(c)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
import numpy as np

stats = np.array([ 
    [20, 70, 30, 80, 50, 30], # should be dropped because it is the same or lower as the next row
    [20, 70, 30, 80, 50, 30], # kept because the in the first value is higher than any other row
    [25, 60, 20, 60, 40, 20], # kept because the in the first value of 25 is higher than any other row
    [20, 40, 30, 80, 50, 40], # kept because the 3rd value of 30 is higher than any other row
])

# 2-dimensional weights array with multiple sets of weights
weights = np.array([
    [3, -4, 2, -2, -1, -1],
    [-2, 1, 2, -2, -1, -1],
    [3, -3, 3, -2, -1, -1],
    [-2, 1, 2, -2, -1, -1],
    # Add more sets of weights as needed, up to 252
])

# Add the weights to the stats array using broadcasting
results = stats + weights

# Function to round down to the nearest 5
def round_down_to_nearest_5(x):
    return x // 5 * 5

# Apply the rounding function using numpy vectorization
rounded_results = round_down_to_nearest_5(results)

# Use numpy's unique function to get unique rows
unique_results = np.unique(rounded_results, axis=0)

# Print the results
print(unique_results)

In [18]:
import numpy as np

def compute_additional_fields(outfits):
    # Create an array to hold the additional fields
    additional_fields = np.zeros((outfits.shape[0], outfits.shape[1] + 6))
    
    # Copy the original outfits array
    additional_fields[:, :outfits.shape[1]] = outfits
    
    # Compute the sum of each attribute with the total points, give the stat a weight of 10
    for i in range(6):
        additional_fields[:, outfits.shape[1] + i] = outfits[:, i] * 10 + outfits[:, 6]
    
    return additional_fields

def find_peak_values(fields):
    # Find the maximum values for each field
    peak_values = np.max(fields, axis=0)
    return peak_values

def is_pinnacle(outfit, peak_values, num_original_fields):
    # Check if the outfit has at least one field at its peak value
    for i in range(num_original_fields, len(outfit)):
        if outfit[i] == peak_values[i]:
            return True
    return False

def find_pinnacle_outfits(outfits):
    additional_fields = compute_additional_fields(outfits)
    peak_values = find_peak_values(additional_fields)
    num_original_fields = outfits.shape[1]
    
    pinnacle_outfits = []
    
    for outfit in additional_fields:
        if is_pinnacle(outfit, peak_values, num_original_fields):
            pinnacle_outfits.append(outfit[:num_original_fields])
    
    return np.array(pinnacle_outfits)

# Example usage
outfits = np.array([
    [20, 70, 30, 80, 50, 30, 280], 
    [20, 70, 30, 80, 50, 30, 280], 
    [25, 60, 20, 60, 40, 20, 225], 
    [20, 40, 30, 80, 50, 40, 260], 
    [20, 70, 30, 80, 50, 25, 275], 
])

pinnacle_outfits = find_pinnacle_outfits(outfits)
print(pinnacle_outfits)


[[ 20.  70.  30.  80.  50.  30. 280.]
 [ 20.  70.  30.  80.  50.  30. 280.]
 [ 20.  40.  30.  80.  50.  40. 260.]]


In [30]:
import numpy as np

# Define the data type for the structured numpy array
dtype = np.dtype([
    ('mobility', np.int64),
    ('resilience', np.int64),
    ('recovery', np.int64),
    ('discipline', np.int64),
    ('intellect', np.int64),
    ('strength', np.int64),
    ('helmet', np.int64),
    ('gauntlets', np.int64),
    ('chest_armor', np.int64),
    ('leg_armor', np.int64),
    ('class_item', np.int64),
    ('num_artifice', np.int64)
])

# outfit_array = np.empty((0,), dtype=dtype)
outfit_array = np.array([(20, 70, 30, 80, 50, 30, 100, 101, 102, 103, 104, 4),
                         (25, 30, 20, 70, 50, 70, 100, 101, 107, 106, 104, 2)], dtype=dtype)

print(outfit_array['num_artifice'])
outfit_array.shape

[4 2]


(2,)

In [20]:
import numpy as np

# Define the structured data type
dt = np.dtype([('Name', np.unicode_, 16), ('Value', np.float64, (1,))])

# Create an array with this data type
arr = np.array([('Position1', 1.0), ('Position2', 2.0)], dtype=dt)

# Access elements by name
print(arr['Name'])
print(arr['Value'])

['Position1' 'Position2']
[[1.]
 [2.]]


In [19]:
import numpy as np

# Initialize an empty list
data = []

# Append data as it becomes available
for _ in range(1000000):  # Replace this with your actual loop
    row = np.random.rand(30)  # Replace this with your actual data
    data.append(row)

# Convert the list to a numpy array
data = np.array(data)

print(data.shape)

(1000000, 30)


In [15]:
import itertools

items = ["mobility", "resilience", "recovery", "discipline", "intellect", "strength"]

# Generate all permutations of length 2
permutations = list(itertools.permutations(items, 3))

# Print the permutations
for p in permutations:
    print(p)

print(len(permutations))    

('mobility', 'resilience', 'recovery')
('mobility', 'resilience', 'discipline')
('mobility', 'resilience', 'intellect')
('mobility', 'resilience', 'strength')
('mobility', 'recovery', 'resilience')
('mobility', 'recovery', 'discipline')
('mobility', 'recovery', 'intellect')
('mobility', 'recovery', 'strength')
('mobility', 'discipline', 'resilience')
('mobility', 'discipline', 'recovery')
('mobility', 'discipline', 'intellect')
('mobility', 'discipline', 'strength')
('mobility', 'intellect', 'resilience')
('mobility', 'intellect', 'recovery')
('mobility', 'intellect', 'discipline')
('mobility', 'intellect', 'strength')
('mobility', 'strength', 'resilience')
('mobility', 'strength', 'recovery')
('mobility', 'strength', 'discipline')
('mobility', 'strength', 'intellect')
('resilience', 'mobility', 'recovery')
('resilience', 'mobility', 'discipline')
('resilience', 'mobility', 'intellect')
('resilience', 'mobility', 'strength')
('resilience', 'recovery', 'mobility')
('resilience', 'recove

In [13]:
import numpy as np

def find_peak_values(outfits):
    # Find the maximum values for each attribute and total points
    peak_values = np.max(outfits, axis=0)
    return peak_values

def is_pinnacle(outfit, peak_values):
    # Check if the outfit has at least one attribute at its peak value
    # and that no other outfit exceeds it in total points
    for i in range(7):  # Check each attribute + total points
        if outfit[i] == peak_values[i]:
            return True
    return False

def find_pinnacle_outfits(outfits):
    peak_values = find_peak_values(outfits)
    pinnacle_outfits = []

    for outfit in outfits:
        if is_pinnacle(outfit, peak_values):
            pinnacle_outfits.append(outfit)
    
    return np.array(pinnacle_outfits)

# Example usage
outfits = np.array([
    [20, 70, 30, 80, 50, 30, 280], 
    [20, 70, 30, 80, 50, 30, 280], 
    [25, 60, 20, 60, 40, 20, 225], 
    [20, 40, 30, 80, 50, 40, 260], 
    [20, 70, 30, 80, 50, 25, 275], 
])

pinnacle_outfits = find_pinnacle_outfits(outfits)
print(pinnacle_outfits)

[[ 20  70  30  80  50  30 280]
 [ 20  70  30  80  50  30 280]
 [ 25  60  20  60  40  20 225]
 [ 20  40  30  80  50  40 260]
 [ 20  70  30  80  50  25 275]]


In [ ]:
import numpy as np

# Original stats array
stats = np.array([17, 74, 33, 82, 51, 31])

# 2-dimensional weights array
weights = np.array([
    [3, -4, 2, -2, -1, -1],
    [-2, 1, 2, -2, -1, -1],
    # Add up to 252 sets of weights
])

# Add the weights to the stats array using broadcasting
results = stats + weights

print(results)

In [4]:
import numpy as np

# Original stats array
stats = np.array([17, 74, 33, 82, 51, 31])

# 2-dimensional weights array with multiple sets of weights
weights = np.array([
    [3, -4, 2, -2, -1, -1],
    [-2, 1, 2, -2, -1, -1],
    [3, -3, 3, -2, -1, -1],
    [-2, 1, 2, -2, -1, -1],
    # Add more sets of weights as needed, up to 252
])

# Add the weights to the stats array using broadcasting
results = stats + weights

# Function to round down to the nearest 5
def round_down_to_nearest_5(x):
    return x // 5 * 5

# Apply the rounding function using numpy vectorization
rounded_results = round_down_to_nearest_5(results)

# Use numpy's unique function to get unique rows
unique_results = np.unique(rounded_results, axis=0)

# Print the results
print(unique_results)

[[15 75 35 80 50 30]
 [20 70 35 80 50 30]]


In [5]:
import numpy as np

# Example 3D array
array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
])

# Find unique 2D slices along the first axis (axis=0)
unique_slices_axis0 = np.unique(array_3d, axis=0)

# Find unique 2D slices along the second axis (axis=1)
unique_slices_axis1 = np.unique(array_3d, axis=1)

# Find unique 1D slices along the third axis (axis=2)
unique_slices_axis2 = np.unique(array_3d, axis=2)

print("Unique slices along axis=0:")
print(unique_slices_axis0)

print("Unique slices along axis=1:")
print(unique_slices_axis1)

print("Unique slices along axis=2:")
print(unique_slices_axis2)

Unique slices along axis=0:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Unique slices along axis=1:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Unique slices along axis=2:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#  Lance DB testing
https://github.com/lancedb/lancedb

In [8]:
%%bash
pip install lancedb
pip install ipywidgets

In [9]:
import lancedb

uri = "data/sample-lancedb"
db = lancedb.connect(uri)
table = db.create_table("my_table",
                         exist_ok=True,
                         data=[{"vector": [3.1, 4.1], "item": "foo", "price": 10.0},
                               {"vector": [5.9, 26.5], "item": "bar", "price": 20.0}])
result = table.search([100, 100]).limit(2).to_pandas()
result

vector item  price     _distance
0  [5.9, 26.5]  bar   20.0  14257.059570
1   [3.1, 4.1]  foo   10.0  18586.421875

In [ ]:
# todo: see what the performance is if we insert all the armor pieces into a lancedb table and then query for the best outfits